### ISSUE TITLE
Is Stable

### ISSUE THREAD

**Issue by ghost** [Ark4ne/phalcon-luxury#11]
Is it stabled to start a big project?

**Comment by Ark4ne** [comment]
I have no application in production using nucleon, however I am building one and all the features of the framework are stable.

So I only can invite you to try :)

What do you mean by "a big project"?

**Comment by ghost** [comment]
A geographic and location-based project for Middle East countries based on openstreetmap facilities and ...

**Comment by Ark4ne** [comment]
I have done a thorough testing of all the features, all working correctly.

I push version 1.0.1 of the "app" / "skeleton" part, I have only brought some fixes on the views of the auth, nothing really impacting.

In any case, the framework remains young, it will quickly evolve, and if there are bugs, let me share, and I will correct them !

Let me known if you have any other question :)

**Comment by ghost** [comment]
Sure , Thank you and good luck.

**Comment by Ark4ne** [comment]
To you too!
