### ISSUE TITLE
Impossible to install a fresh project

### ISSUE THREAD

**Issue by netwarp** [Ark4ne/phalcon-luxury#17]
Hello,
I launch a fresh installation with this command: composer create-project --prefer-dist nucleon/nucleon app-root
I have this error message:

>  Declaration of Neutrino\Foundation\Kernelize::registerModules(array $modules, $merge = false) must be compatible with Phalcon\Application\AbstractApplication::registerModules(array $modules, bool $merge = NULL): Phalcon\Application\AbstractApplication in C:\Users\toto\projects\app-root\vendor\nucleon\framework\src\Neutrino\Foundation\Cli\Kernel.php on line 70

Config: windows 10, PHP 7.4, Phalcon 4.
Thanks for your help

**Comment by Ark4ne** [comment]
Hello,

For the moment, the nucleon is not compatible with phalcon 4.

I am working on nucleon 2.0 which will be compatible with phalcon 4 and PHP 7.4.

Meanwhile, nucleon remains usable with phalcon 3.4 and PHP 7.3.

**Comment by Ark4ne** [comment]
Close in favor of : 
[phalcon-nucleon/nucleon/issues/18](https://github.com/phalcon-nucleon/nucleon/issues/18)
and
[phalcon-nucleon/framework/issues/68](https://github.com/phalcon-nucleon/framework/issues/68)
